FROM debian:stable-20240812-slim

# add wget, zsh, and git for ohmhzsh install + general use
# add vim-tiny for basic file editing w/o full vim pkg 
RUN apt update && apt install -y \
    wget \
    vim-tiny \
    && rm -rf /var/lib/apt/lists/*